server:
  port: 5055

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: wallet-service-route
              uri: http://wallet-service:5050
              predicates:
                - Path=/api/wallet/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: api-docs-wallet-route
              uri: http://wallet-service:5050
              predicates:
                - Path=/api-docs/wallet
              filters:
                - RewritePath=/api-docs/wallet,/v3/api-docs

            - id: auth-service
              uri: http://auth-service:5051
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: api-docs-auth-route
              uri: http://auth-service:5051
              predicates:cd git
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs