CREATE TABLE IF NOT EXISTS wallets (
   id UUID PRIMARY KEY,
   user_id UUID NOT NULL UNIQUE,
   balance NUMERIC(19, 4) NOT NULL DEFAULT 0.0,
   currency VARCHAR(3) NOT NULL DEFAULT 'PHP',
   status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
   last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


