### Login Request to retrieve a token
POST http://localhost:5055/auth/login
Content-Type: application/json

{
  "phoneNumber": "09052180351",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}}