### Register a new account
POST http://localhost:5055/auth/registration
Content-Type: application/json

{
  "email": "roeder.aringoy21@gmail.com",
  "phoneNumber": "09687726205",
  "password": "$2b$12$7hoRZfJrRKD2nIm2vHLs7OBETy.LWenXXMLKf99W8M4PUwO6KB7fu",
  "firstName": "",
  "lastName": "Aringoy",
  "role": "USER",
  "address": "Paciano Rizal",
  "dateOfBirth": "1991-10-21"
}