CREATE TABLE IF NOT EXISTS accounts (
id UUID PRIMARY KEY,
user_id UUID NOT NULL UNIQUE,
first_name VARCHAR(100) NOT NULL ,
last_name VARCHAR(100) NOT NULL ,
address VARCHAR(100) NOT NULL,
date_of_birth VARCHAR(100) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);